[env:lolin_s3_mini]
platform = espressif32
board = lolin_s3_mini
framework = arduino
monitor_speed = 115200
lib_deps = 
	jgromes/RadioLib@^6.6.0
	adafruit/Adafruit BME280 Library@^2.2.4
	adafruit/Adafruit BNO055@^1.6.3
	adafruit/Adafruit Unified Sensor@^1.1.14
	mikalhart/TinyGPSPlus@^1.0.3
	bblanchon/ArduinoJson@^7.0.4
