[env:lolin_s3_mini]
platform = espressif32
board = lolin_s3_mini
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
lib_deps = 
	jgromes/RadioLib@^6.6.0
	bblanchon/ArduinoJson@^7.0.4
